name: Rubi CI

on: [push]


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.4
      - run: bundle install
      - run bundle exec rcpes
